FROM python:3.12-slim@sha256:85824326bc4ae27a1abb5bc0dd9e08847aa5fe73d8afb593b1b45b7cb4180f57
ARG TOKEN

ENV DEBIAN_FRONTEND=noninteractive
ENV POETRY_VERSION="2.1.0"
ENV POETRY_NO_INTERACTION=1
ENV POETRY_VIRTUALENVS_CREATE=0
ENV POETRY_VIRTUALENVS_IN_PROJECT=0

ENV POETRY_HTTP_BASIC_PYTHONMONTY_USERNAME="docker-user"
ENV POETRY_HTTP_BASIC_PYTHONMONTY_PASSWORD="$TOKEN"
RUN echo "$POETRY_HTTP_BASIC_FOO_PASSWORD"

RUN apt-get update
RUN apt-get install -y --no-install-recommends libpq5=15.12-0+deb12u2

WORKDIR /app
COPY . .

RUN pip install poetry=="$POETRY_VERSION"
RUN poetry install

CMD ["python", "cat_app/app.py"]
