name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  security-events: write

env:
  IMAGE_NAME: 0-original
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget gnupg -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Build Docker image
        run: |
          docker build \
            --build-arg TOKEN=${{ secrets.PYTHONMONTY_ADO_PAT }} \
            -f docker/0_original.Dockerfile \
            -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Run Trivy image scan
        run: |
          trivy image --format sarif -o trivy-image.sarif $IMAGE_NAME:$IMAGE_TAG

      - name: Upload image scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-image.sarif

      - name: Run Trivy config scan (Dockerfile best practices)
        run: |
          trivy config --format sarif -o trivy-config.sarif .

      - name: Upload config scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-config.sarif
